name: Telegram YouTube Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      LINKBOX_API_TOKEN: ${{ secrets.LINKBOX_API_TOKEN }}
      LINKBOX_FOLDER_ID: ${{ secrets.LINKBOX_FOLDER_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Telegram bot
        run: python bot/bot.py
