name: Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot yt-dlp requests
      - name: Run Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          LINKBOX_API_TOKEN: ${{ secrets.LINKBOX_API_TOKEN }}
          LINKBOX_FOLDER_ID: ${{ secrets.LINKBOX_FOLDER_ID }}
        run: python bot/bot.py
